name: Build Docker Image and Export as Artifact

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build -t my-image:latest .

    - name: Save Docker image to tar
      run: |
        docker save my-image:latest -o my-image.tar

    - name: Upload image tar as artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-image-tar
        path: my-image.tar
