name: Build Docker Image and Export as Artifact

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build -t v2ray:latest .

    - name: Save Docker image to tar
      run: |
        docker save v2ray:latest -o v2ray.tar

    - name: Upload image tar as artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-image-tar
        path: v2ray.tar
